on:
  push:
    branches:
      - main

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: List container directory
        uses: Telefonica/openplatform-ci-action@main
        id: directory
        with:
          ci user: contint-low-level-iptv
          ci token: ${{ secrets.CONTINT_LOW_LEVEL_IPTV_TOKEN }}
          contint token art: ${{ secrets.CONTINT_TOKEN_ART }}
          artifactory url: https://artifactory.hi.inet/artifactory
          tlf bfw: openplatform-tlfbfw
          args: this are the options
        - name: Get the directory output
        run: echo "${{ steps.directory.outputs.output_message }}"
